name: Continuous Integration

on:
  push:
    branches: [ main, develop, 'feature/*' ]
  pull_request:
    branches: [ main, develop ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_QUICK: ${{ github.repository }}/velocitas-quick

jobs:
  build-quick:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Quick Build image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.quick
        push: false
        tags: velocitas-quick:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

  publish-dev-images:
    runs-on: ubuntu-latest
    needs: [build-quick]
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push development images
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.quick
        platforms: linux/amd64
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_QUICK }}:develop
        cache-from: type=gha
        cache-to: type=gha,mode=max

  notify-status:
    runs-on: ubuntu-latest
    needs: [build-quick]
    if: always()
    
    steps:
    - name: Report CI status
      run: |
        if [ "${{ needs.build-quick.result }}" = "success" ]; then
          echo "🎉 CI build completed successfully!"
        else
          echo "❌ CI build failed:"
          echo "  - Build Quick: ${{ needs.build-quick.result }}"
          exit 1
        fi